create extension if not exists "wrappers" with schema "extensions";


create type "public"."lexicon_type" as enum ('part', 'workflow_template', 'step_template', 'document', 'spec', 'client');

create type "public"."object_priority" as enum ('low', 'medium', 'high', 'urgent');

create type "public"."relation_kind" as enum ('electrical_connection', 'signals_to', 'mechanical', 'references', 'contains', 'depends_on');

create sequence "public"."files_id_seq";

create sequence "public"."lexicon_items_id_seq";

create sequence "public"."object_relations_id_seq";

create sequence "public"."object_subtasks_id_seq";

create sequence "public"."objects_id_seq";

create sequence "public"."projects_id_seq";

create sequence "public"."steps_id_seq";

create sequence "public"."workflows_id_seq";

create table "public"."boards" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" text,
    "description" text,
    "color" text default '''bg-blue-500''::text'::text,
    "user_id" text not null,
    "updated_at" timestamp without time zone default now()
);


alter table "public"."boards" enable row level security;

create table "public"."columns" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "board_id" bigint,
    "title" text not null,
    "sort_order" integer default 0,
    "user_id" text not null
);


alter table "public"."columns" enable row level security;

create table "public"."files" (
    "id" bigint not null default nextval('files_id_seq'::regclass),
    "created_at" timestamp with time zone not null default now(),
    "uploaded_by" text,
    "org_id" text not null,
    "project_id" bigint,
    "storage_key" text not null,
    "filename" text not null,
    "mime_type" text,
    "size_bytes" bigint,
    "sha256" text
);


alter table "public"."files" enable row level security;

create table "public"."lexicon_files" (
    "lexicon_id" bigint not null,
    "file_id" bigint not null
);


alter table "public"."lexicon_files" enable row level security;

create table "public"."lexicon_items" (
    "id" bigint not null default nextval('lexicon_items_id_seq'::regclass),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "org_id" text not null,
    "type" lexicon_type not null,
    "name" text not null,
    "sku" text,
    "manufacturer" text,
    "attributes" jsonb not null default '{}'::jsonb,
    "version" smallint not null default '1'::smallint
);


alter table "public"."lexicon_items" enable row level security;

create table "public"."object_files" (
    "object_id" bigint not null,
    "file_id" bigint not null
);


alter table "public"."object_files" enable row level security;

create table "public"."object_lexicon_links" (
    "object_id" bigint not null,
    "lexicon_id" bigint not null,
    "note" text
);


alter table "public"."object_lexicon_links" enable row level security;

create table "public"."object_relations" (
    "id" bigint not null default nextval('object_relations_id_seq'::regclass),
    "created_at" timestamp with time zone not null default now(),
    "relation_kind" relation_kind not null,
    "src_object_id" bigint not null,
    "dst_object_id" bigint not null
);


alter table "public"."object_relations" enable row level security;

create table "public"."object_subtasks" (
    "id" bigint not null default nextval('object_subtasks_id_seq'::regclass),
    "object_id" bigint not null,
    "title" text not null,
    "is_done" boolean not null default false,
    "sort_order" integer not null default 0
);


alter table "public"."object_subtasks" enable row level security;

create table "public"."objects" (
    "id" bigint not null default nextval('objects_id_seq'::regclass),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "project_id" bigint not null,
    "workflow_id" bigint[],
    "step_id" bigint[],
    "title" text not null,
    "description_md" text,
    "assignee" text,
    "due_date" date,
    "priority" object_priority default 'medium'::object_priority,
    "sort_order" integer default 0,
    "metadata" jsonb
);


alter table "public"."objects" enable row level security;

create table "public"."projects" (
    "id" bigint not null default nextval('projects_id_seq'::regclass),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "org_id" text not null,
    "name" text not null,
    "code" text,
    "description" text,
    "status" text default 'active'::text,
    "start_date" date,
    "end_date" date,
    "metadata" jsonb not null default '{}'::jsonb,
    "client_lexicon_id" bigint
);


alter table "public"."projects" enable row level security;

create table "public"."steps" (
    "id" bigint not null default nextval('steps_id_seq'::regclass),
    "created_at" timestamp with time zone not null default now(),
    "workflow_id" bigint not null,
    "title" text not null,
    "position" integer not null
);


alter table "public"."steps" enable row level security;

create table "public"."tasks" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" text not null,
    "description" text,
    "assignee" text,
    "due_date" date,
    "priority" text default '''medium''::text'::text,
    "sort_order" integer default 0,
    "column_id" bigint
);


alter table "public"."tasks" enable row level security;

create table "public"."workflows" (
    "id" bigint not null default nextval('workflows_id_seq'::regclass),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "project_id" bigint not null,
    "name" text not null,
    "description" text,
    "color" text default 'bg-blue-500'::text
);


alter table "public"."workflows" enable row level security;

alter sequence "public"."files_id_seq" owned by "public"."files"."id";

alter sequence "public"."lexicon_items_id_seq" owned by "public"."lexicon_items"."id";

alter sequence "public"."object_relations_id_seq" owned by "public"."object_relations"."id";

alter sequence "public"."object_subtasks_id_seq" owned by "public"."object_subtasks"."id";

alter sequence "public"."objects_id_seq" owned by "public"."objects"."id";

alter sequence "public"."projects_id_seq" owned by "public"."projects"."id";

alter sequence "public"."steps_id_seq" owned by "public"."steps"."id";

alter sequence "public"."workflows_id_seq" owned by "public"."workflows"."id";

CREATE UNIQUE INDEX boards_pkey ON public.boards USING btree (id);

CREATE UNIQUE INDEX columns_pkey ON public.columns USING btree (id);

CREATE INDEX files_org_idx ON public.files USING btree (org_id);

CREATE UNIQUE INDEX files_pkey ON public.files USING btree (id);

CREATE INDEX files_project_idx ON public.files USING btree (project_id);

CREATE INDEX lexicon_attrs_gin ON public.lexicon_items USING gin (attributes jsonb_path_ops);

CREATE UNIQUE INDEX lexicon_files_pkey ON public.lexicon_files USING btree (lexicon_id, file_id);

CREATE UNIQUE INDEX lexicon_items_org_id_type_name_key ON public.lexicon_items USING btree (org_id, type, name);

CREATE UNIQUE INDEX lexicon_items_pkey ON public.lexicon_items USING btree (id);

CREATE INDEX lexicon_org_type_name_idx ON public.lexicon_items USING btree (org_id, type, name);

CREATE UNIQUE INDEX object_files_pkey ON public.object_files USING btree (object_id, file_id);

CREATE UNIQUE INDEX object_lexicon_links_pkey ON public.object_lexicon_links USING btree (object_id, lexicon_id);

CREATE UNIQUE INDEX object_relations_pkey ON public.object_relations USING btree (id);

CREATE UNIQUE INDEX object_subtasks_pkey ON public.object_subtasks USING btree (id);

CREATE UNIQUE INDEX objects_pkey ON public.objects USING btree (id);

CREATE INDEX objects_project_idx ON public.objects USING btree (project_id);

CREATE INDEX objects_search_idx ON public.objects USING gin (to_tsvector('simple'::regconfig, ((COALESCE(title, ''::text) || ' '::text) || COALESCE(description_md, ''::text))));

CREATE INDEX objects_step_idx ON public.objects USING btree (step_id);

CREATE INDEX objects_workflow_idx ON public.objects USING btree (workflow_id);

CREATE INDEX objrel_dst_idx ON public.object_relations USING btree (dst_object_id);

CREATE INDEX objrel_kind_idx ON public.object_relations USING btree (relation_kind);

CREATE INDEX objrel_src_idx ON public.object_relations USING btree (src_object_id);

CREATE UNIQUE INDEX objrel_undirected_unique ON public.object_relations USING btree (LEAST(src_object_id, dst_object_id), GREATEST(src_object_id, dst_object_id), relation_kind) WHERE (relation_kind = ANY (ARRAY['mechanical'::relation_kind, 'contains'::relation_kind, 'references'::relation_kind]));

CREATE INDEX projects_clientlex_idx ON public.projects USING btree (client_lexicon_id);

CREATE INDEX projects_meta_gin ON public.projects USING gin (metadata jsonb_path_ops);

CREATE UNIQUE INDEX projects_org_id_code_key ON public.projects USING btree (org_id, code) NULLS NOT DISTINCT;

CREATE UNIQUE INDEX projects_org_id_name_key ON public.projects USING btree (org_id, name);

CREATE INDEX projects_org_idx ON public.projects USING btree (org_id);

CREATE UNIQUE INDEX projects_pkey ON public.projects USING btree (id);

CREATE INDEX projects_status_idx ON public.projects USING btree (status);

CREATE UNIQUE INDEX steps_pkey ON public.steps USING btree (id);

CREATE UNIQUE INDEX steps_workflow_id_position_key ON public.steps USING btree (workflow_id, "position");

CREATE UNIQUE INDEX steps_workflow_id_title_key ON public.steps USING btree (workflow_id, title);

CREATE INDEX steps_workflow_idx ON public.steps USING btree (workflow_id);

CREATE INDEX subtasks_object_idx ON public.object_subtasks USING btree (object_id);

CREATE UNIQUE INDEX tasks_pkey ON public.tasks USING btree (id);

CREATE UNIQUE INDEX workflows_pkey ON public.workflows USING btree (id);

CREATE INDEX workflows_project_idx ON public.workflows USING btree (project_id);

alter table "public"."boards" add constraint "boards_pkey" PRIMARY KEY using index "boards_pkey";

alter table "public"."columns" add constraint "columns_pkey" PRIMARY KEY using index "columns_pkey";

alter table "public"."files" add constraint "files_pkey" PRIMARY KEY using index "files_pkey";

alter table "public"."lexicon_files" add constraint "lexicon_files_pkey" PRIMARY KEY using index "lexicon_files_pkey";

alter table "public"."lexicon_items" add constraint "lexicon_items_pkey" PRIMARY KEY using index "lexicon_items_pkey";

alter table "public"."object_files" add constraint "object_files_pkey" PRIMARY KEY using index "object_files_pkey";

alter table "public"."object_lexicon_links" add constraint "object_lexicon_links_pkey" PRIMARY KEY using index "object_lexicon_links_pkey";

alter table "public"."object_relations" add constraint "object_relations_pkey" PRIMARY KEY using index "object_relations_pkey";

alter table "public"."object_subtasks" add constraint "object_subtasks_pkey" PRIMARY KEY using index "object_subtasks_pkey";

alter table "public"."objects" add constraint "objects_pkey" PRIMARY KEY using index "objects_pkey";

alter table "public"."projects" add constraint "projects_pkey" PRIMARY KEY using index "projects_pkey";

alter table "public"."steps" add constraint "steps_pkey" PRIMARY KEY using index "steps_pkey";

alter table "public"."tasks" add constraint "tasks_pkey" PRIMARY KEY using index "tasks_pkey";

alter table "public"."workflows" add constraint "workflows_pkey" PRIMARY KEY using index "workflows_pkey";

alter table "public"."columns" add constraint "columns_board_id_fkey" FOREIGN KEY (board_id) REFERENCES boards(id) ON DELETE CASCADE not valid;

alter table "public"."columns" validate constraint "columns_board_id_fkey";

alter table "public"."files" add constraint "files_project_id_fkey" FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE not valid;

alter table "public"."files" validate constraint "files_project_id_fkey";

alter table "public"."lexicon_files" add constraint "lexicon_files_file_id_fkey" FOREIGN KEY (file_id) REFERENCES files(id) ON DELETE CASCADE not valid;

alter table "public"."lexicon_files" validate constraint "lexicon_files_file_id_fkey";

alter table "public"."lexicon_files" add constraint "lexicon_files_lexicon_id_fkey" FOREIGN KEY (lexicon_id) REFERENCES lexicon_items(id) not valid;

alter table "public"."lexicon_files" validate constraint "lexicon_files_lexicon_id_fkey";

alter table "public"."lexicon_items" add constraint "lexicon_items_org_id_type_name_key" UNIQUE using index "lexicon_items_org_id_type_name_key";

alter table "public"."object_files" add constraint "object_files_file_id_fkey" FOREIGN KEY (file_id) REFERENCES files(id) ON DELETE CASCADE not valid;

alter table "public"."object_files" validate constraint "object_files_file_id_fkey";

alter table "public"."object_files" add constraint "object_files_object_id_fkey" FOREIGN KEY (object_id) REFERENCES objects(id) ON DELETE CASCADE not valid;

alter table "public"."object_files" validate constraint "object_files_object_id_fkey";

alter table "public"."object_lexicon_links" add constraint "object_lexicon_links_lexicon_id_fkey" FOREIGN KEY (lexicon_id) REFERENCES lexicon_items(id) not valid;

alter table "public"."object_lexicon_links" validate constraint "object_lexicon_links_lexicon_id_fkey";

alter table "public"."object_lexicon_links" add constraint "object_lexicon_links_object_id_fkey" FOREIGN KEY (object_id) REFERENCES objects(id) not valid;

alter table "public"."object_lexicon_links" validate constraint "object_lexicon_links_object_id_fkey";

alter table "public"."object_relations" add constraint "object_relations_dst_object_id_fkey" FOREIGN KEY (dst_object_id) REFERENCES objects(id) ON DELETE CASCADE not valid;

alter table "public"."object_relations" validate constraint "object_relations_dst_object_id_fkey";

alter table "public"."object_relations" add constraint "object_relations_no_self" CHECK ((src_object_id <> dst_object_id)) not valid;

alter table "public"."object_relations" validate constraint "object_relations_no_self";

alter table "public"."object_relations" add constraint "object_relations_src_object_id_fkey" FOREIGN KEY (src_object_id) REFERENCES objects(id) ON DELETE CASCADE not valid;

alter table "public"."object_relations" validate constraint "object_relations_src_object_id_fkey";

alter table "public"."object_subtasks" add constraint "object_subtasks_object_id_fkey" FOREIGN KEY (object_id) REFERENCES objects(id) ON DELETE CASCADE not valid;

alter table "public"."object_subtasks" validate constraint "object_subtasks_object_id_fkey";

alter table "public"."objects" add constraint "objects_project_id_fkey" FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE not valid;

alter table "public"."objects" validate constraint "objects_project_id_fkey";

alter table "public"."projects" add constraint "projects_client_lexicon_fk" FOREIGN KEY (client_lexicon_id) REFERENCES lexicon_items(id) ON DELETE SET NULL not valid;

alter table "public"."projects" validate constraint "projects_client_lexicon_fk";

alter table "public"."projects" add constraint "projects_org_id_code_key" UNIQUE using index "projects_org_id_code_key";

alter table "public"."projects" add constraint "projects_org_id_name_key" UNIQUE using index "projects_org_id_name_key";

alter table "public"."steps" add constraint "steps_workflow_id_fkey" FOREIGN KEY (workflow_id) REFERENCES workflows(id) ON DELETE CASCADE not valid;

alter table "public"."steps" validate constraint "steps_workflow_id_fkey";

alter table "public"."steps" add constraint "steps_workflow_id_position_key" UNIQUE using index "steps_workflow_id_position_key";

alter table "public"."steps" add constraint "steps_workflow_id_title_key" UNIQUE using index "steps_workflow_id_title_key";

alter table "public"."tasks" add constraint "tasks_column_id_fkey" FOREIGN KEY (column_id) REFERENCES columns(id) ON DELETE CASCADE not valid;

alter table "public"."tasks" validate constraint "tasks_column_id_fkey";

alter table "public"."workflows" add constraint "workflows_project_id_fkey" FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE not valid;

alter table "public"."workflows" validate constraint "workflows_project_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.auth_org_id()
 RETURNS text
 LANGUAGE sql
 STABLE
AS $function$
  SELECT coalesce((current_setting('request.jwt.claims', true))::jsonb ->> 'org_id', '');
$function$
;

CREATE OR REPLACE FUNCTION public.ensure_client_lexicon_type()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  IF NEW.client_lexicon_id IS NULL THEN
    RETURN NEW;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.lexicon_items li
    WHERE li.id = NEW.client_lexicon_id
      AND li.type = 'client'
      AND li.org_id = NEW.org_id
  ) THEN
    RAISE EXCEPTION
      'client_lexicon_id % must reference a lexicon_items row of type=client within the same org %',
      NEW.client_lexicon_id, NEW.org_id
      USING ERRCODE = '23514';
  END IF;

  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.requesting_user_id()
 RETURNS text
 LANGUAGE sql
 STABLE
AS $function$SELECT NULLIF(
    current_setting('request.jwt.claims', true)::json ->>'sub',
    ''
  )::text;$function$
;

CREATE OR REPLACE FUNCTION public.set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END; $function$
;

create policy "Users can delete their own boards"
on "public"."boards"
as permissive
for delete
to public
using ((requesting_user_id() = user_id));


create policy "Users can insert their own boards"
on "public"."boards"
as permissive
for insert
to public
with check ((requesting_user_id() = user_id));


create policy "Users can update their own boards"
on "public"."boards"
as permissive
for update
to public
using ((requesting_user_id() = user_id));


create policy "Users can view their own boards"
on "public"."boards"
as permissive
for select
to public
using ((requesting_user_id() = user_id));


create policy "Users can delete columns from their own boards"
on "public"."columns"
as permissive
for delete
to public
using ((EXISTS ( SELECT 1
   FROM boards
  WHERE ((boards.id = columns.board_id) AND (boards.user_id = requesting_user_id())))));


create policy "Users can insert columns from their own boards"
on "public"."columns"
as permissive
for insert
to public
with check ((EXISTS ( SELECT 1
   FROM boards
  WHERE ((boards.id = columns.board_id) AND (boards.user_id = requesting_user_id())))));


create policy "Users can update columns from their own boards"
on "public"."columns"
as permissive
for update
to public
using ((EXISTS ( SELECT 1
   FROM boards
  WHERE ((boards.id = columns.board_id) AND (boards.user_id = requesting_user_id())))));


create policy "Users can view columns from their own boards"
on "public"."columns"
as permissive
for select
to public
using ((EXISTS ( SELECT 1
   FROM boards
  WHERE ((boards.id = columns.board_id) AND (boards.user_id = requesting_user_id())))));


create policy "org_files_all"
on "public"."files"
as permissive
for all
to public
using ((org_id = auth_org_id()))
with check ((org_id = auth_org_id()));


create policy "org_lexicon_to_files_all"
on "public"."lexicon_files"
as permissive
for all
to public
using (((lexicon_id IN ( SELECT lexicon_items.id
   FROM lexicon_items
  WHERE (lexicon_items.org_id = auth_org_id()))) AND (file_id IN ( SELECT files.id
   FROM files
  WHERE (files.org_id = auth_org_id())))))
with check (((lexicon_id IN ( SELECT lexicon_items.id
   FROM lexicon_items
  WHERE (lexicon_items.org_id = auth_org_id()))) AND (file_id IN ( SELECT files.id
   FROM files
  WHERE (files.org_id = auth_org_id())))));


create policy "org_lexicon_all"
on "public"."lexicon_items"
as permissive
for all
to public
using ((org_id = auth_org_id()))
with check ((org_id = auth_org_id()));


create policy "org_object_files_all"
on "public"."object_files"
as permissive
for all
to public
using (((object_id IN ( SELECT objects.id
   FROM objects
  WHERE (objects.project_id IN ( SELECT projects.id
           FROM projects
          WHERE (projects.org_id = auth_org_id()))))) AND (file_id IN ( SELECT files.id
   FROM files
  WHERE (files.org_id = auth_org_id())))))
with check (((object_id IN ( SELECT objects.id
   FROM objects
  WHERE (objects.project_id IN ( SELECT projects.id
           FROM projects
          WHERE (projects.org_id = auth_org_id()))))) AND (file_id IN ( SELECT files.id
   FROM files
  WHERE (files.org_id = auth_org_id())))));


create policy "org_obj_lex_links_all"
on "public"."object_lexicon_links"
as permissive
for all
to public
using (((object_id IN ( SELECT objects.id
   FROM objects
  WHERE (objects.project_id IN ( SELECT projects.id
           FROM projects
          WHERE (projects.org_id = auth_org_id()))))) AND (lexicon_id IN ( SELECT lexicon_items.id
   FROM lexicon_items
  WHERE (lexicon_items.org_id = auth_org_id())))))
with check (((object_id IN ( SELECT objects.id
   FROM objects
  WHERE (objects.project_id IN ( SELECT projects.id
           FROM projects
          WHERE (projects.org_id = auth_org_id()))))) AND (lexicon_id IN ( SELECT lexicon_items.id
   FROM lexicon_items
  WHERE (lexicon_items.org_id = auth_org_id())))));


create policy "org_object_relations_all"
on "public"."object_relations"
as permissive
for all
to public
using (((src_object_id IN ( SELECT objects.id
   FROM objects
  WHERE (objects.project_id IN ( SELECT projects.id
           FROM projects
          WHERE (projects.org_id = auth_org_id()))))) AND (dst_object_id IN ( SELECT objects.id
   FROM objects
  WHERE (objects.project_id IN ( SELECT projects.id
           FROM projects
          WHERE (projects.org_id = auth_org_id())))))))
with check (((src_object_id IN ( SELECT objects.id
   FROM objects
  WHERE (objects.project_id IN ( SELECT projects.id
           FROM projects
          WHERE (projects.org_id = auth_org_id()))))) AND (dst_object_id IN ( SELECT objects.id
   FROM objects
  WHERE (objects.project_id IN ( SELECT projects.id
           FROM projects
          WHERE (projects.org_id = auth_org_id())))))));


create policy "org_object_subtasks_all"
on "public"."object_subtasks"
as permissive
for all
to public
using ((object_id IN ( SELECT objects.id
   FROM objects
  WHERE (objects.project_id IN ( SELECT projects.id
           FROM projects
          WHERE (projects.org_id = auth_org_id()))))))
with check ((object_id IN ( SELECT objects.id
   FROM objects
  WHERE (objects.project_id IN ( SELECT projects.id
           FROM projects
          WHERE (projects.org_id = auth_org_id()))))));


create policy "org_objects_all"
on "public"."objects"
as permissive
for all
to public
using ((project_id IN ( SELECT projects.id
   FROM projects
  WHERE (projects.org_id = auth_org_id()))))
with check ((project_id IN ( SELECT projects.id
   FROM projects
  WHERE (projects.org_id = auth_org_id()))));


create policy "org_projects_delete"
on "public"."projects"
as permissive
for delete
to public
using ((org_id = auth_org_id()));


create policy "org_projects_insert"
on "public"."projects"
as permissive
for insert
to public
with check ((org_id = auth_org_id()));


create policy "org_projects_select"
on "public"."projects"
as permissive
for select
to public
using ((org_id = auth_org_id()));


create policy "org_projects_update"
on "public"."projects"
as permissive
for update
to public
using ((org_id = auth_org_id()))
with check ((org_id = auth_org_id()));


create policy "org_steps_all"
on "public"."steps"
as permissive
for all
to public
using ((workflow_id IN ( SELECT w.id
   FROM (workflows w
     JOIN projects p ON ((p.id = w.project_id)))
  WHERE (p.org_id = auth_org_id()))))
with check ((workflow_id IN ( SELECT w.id
   FROM (workflows w
     JOIN projects p ON ((p.id = w.project_id)))
  WHERE (p.org_id = auth_org_id()))));


create policy "Users can delete tasks from their own boards"
on "public"."tasks"
as permissive
for delete
to public
using ((EXISTS ( SELECT 1
   FROM (columns
     JOIN boards ON ((boards.id = columns.board_id)))
  WHERE ((columns.id = tasks.column_id) AND (boards.user_id = requesting_user_id())))));


create policy "Users can insert tasks into their own boards"
on "public"."tasks"
as permissive
for insert
to public
with check ((EXISTS ( SELECT 1
   FROM (columns
     JOIN boards ON ((boards.id = columns.board_id)))
  WHERE ((columns.id = tasks.column_id) AND (boards.user_id = requesting_user_id())))));


create policy "Users can update tasks from their own boards"
on "public"."tasks"
as permissive
for update
to public
using ((EXISTS ( SELECT 1
   FROM (columns
     JOIN boards ON ((boards.id = columns.board_id)))
  WHERE ((columns.id = tasks.column_id) AND (boards.user_id = requesting_user_id())))))
with check ((EXISTS ( SELECT 1
   FROM (columns
     JOIN boards ON ((boards.id = columns.board_id)))
  WHERE ((columns.id = tasks.column_id) AND (boards.user_id = requesting_user_id())))));


create policy "Users can view tasks from their own boards"
on "public"."tasks"
as permissive
for select
to public
using ((EXISTS ( SELECT 1
   FROM (columns
     JOIN boards ON ((boards.id = columns.board_id)))
  WHERE ((columns.id = tasks.column_id) AND (boards.user_id = requesting_user_id())))));


create policy "org_workflows_all"
on "public"."workflows"
as permissive
for all
to public
using ((project_id IN ( SELECT projects.id
   FROM projects
  WHERE (projects.org_id = auth_org_id()))))
with check ((project_id IN ( SELECT projects.id
   FROM projects
  WHERE (projects.org_id = auth_org_id()))));


CREATE TRIGGER trg_lexicon_updated BEFORE UPDATE ON public.lexicon_items FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_objects_updated BEFORE UPDATE ON public.objects FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE CONSTRAINT TRIGGER trg_projects_client_type AFTER INSERT OR UPDATE OF client_lexicon_id, org_id ON public.projects DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION ensure_client_lexicon_type();

CREATE TRIGGER trg_projects_updated BEFORE UPDATE ON public.projects FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_workflows_updated BEFORE UPDATE ON public.workflows FOR EACH ROW EXECUTE FUNCTION set_updated_at();



